name: E2E
on: 
  workflow_dispatch:

jobs:
  build:
    name: "Start E2E Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm test